version: '3.7'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf 
    volumes:
      - ./redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - DevOPs
    environment:
      - REDIS_REPLICATION_MODE=master  

  web1:
    restart: unless-stopped
    container_name: web1
    build: ./web1
    ports:
      - 81:5000
    networks:
      - DevOPs  
    depends_on:
      - redis
  web2:
    restart: unless-stopped
    container_name: web2
    build: ./web2
    ports:
      - 82:5000
    networks:
      - DevOPs
    depends_on:
      - redis  

  nginx:
    restart: unless-stopped
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    networks:
      - DevOPs
    depends_on:
      - web1
      - web2

networks:
  DevOPs:
    driver: bridge
volumes:
  redis: {}    
